[package]
name = "sbaitso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tts = "0.25.6"
#[tts macOS deps]
cocoa-foundation = "0.1.2"
env_logger = "0.10.0"
objc = "0.2.7"

