import { VerticalBox, HorizontalBox, Slider} from "std-widgets.slint";
export component MainWindow inherits Window {
    width: 270px;
    height: 480px;

    in property <float> power_level;
    property <float> power_goal;

    callback power_goal_changed(float);

    VerticalBox { 
        Text {
            text: "Power Goal is \{power_goal}";
            color: white;
        }
        Text {
            text: "Power Level is \{power_level}";
            color: white;
        }
        HorizontalBox {
            alignment: center;

            VerticalBox { 
                Slider {
                    width: 60px;
                    height: 100px;
                    orientation: vertical;
                    value: 0;
                    minimum: 0;
                    maximum: 1000;
    
                    changed(change) => {
                        root.power_goal = change;
                        root.power_goal_changed(change);
                    }
                }
                Text {
                    text: "Power";
                }
            }
        }
    }
}