import { VerticalBox, HorizontalBox, Slider} from "std-widgets.slint";
export component MainWindow inherits Window {
    width: 270px;
    height: 480px;

    in property <float> temperature_level;
    property <float> temperature_goal;

    callback temperature_goal_changed(float);

    VerticalBox { 
        Text {
            text: "Temperature Goal is \{Math.round(temperature_goal)}";
            color: white;
        }
        Text {
            text: "Temperature Level is \{Math.round(temperature_level)}";
            color: white;
        }
        HorizontalBox {
            alignment: center;

            VerticalBox { 
                Slider {
                    width: 60px;
                    height: 100px;
                    orientation: vertical;
                    value: 0;
                    minimum: 0;
                    maximum: 500;
    
                    changed(change) => {
                        root.temperature_goal = change;
                        root.temperature_goal_changed(change);
                    }
                }
                Text {
                    text: "Temperature";
                }
            }
        }
    }
}